FALSE_POSITIVES = [
"we should go for a bike ride along the beach",
"computer",
"benefits",
"whats your opinion on the latest political news",
"the phones batterys low",
"mean not sure",
"whos turning on the tv",
"the bathrooms occupied",
"we should plan a picnic in the park this weekend",
"im thinking of rearranging the furniture in the living room",
"fitness",
"reservations",
"im considering joining a yoga class",
"lets take a break",
"im excited about the new restaurant opening",
"news headlines check",
"do you want me to pick up some wine for dinner",
"im planning to take a gardening class",
"have you tried the new restaurant on main street",
"medication",
"put away laundry",
"tired",
"wheres the dogs bowl",
"take",
"im thinking of taking up painting as a hobby",
"im planning to take a cooking class",
"rental",
"lets clean the kitchen",
"do you want me to pick up some eggs on my way home",
"date today",
"im feeling a bit under the weather today",
"im going to fix that loose doorknob",
"dont forget to lock the door",
"the phones charging",
"trash take out",
"ill take out the trash",
"the lights flickered",
"hear noise",
"household",
"waste",
"camping",
"schedule",
"date",
"today",
"the bathroom sink is clogged again",
"we should plan a day trip to the beach",
"can you close the blinds",
"email check",
"i need to pick up some groceries after work",
"we should plan a family game night",
"the fridge is open",
"i need to call the insurance company",
"whos doing dishes tonight",
"time to vacuum",
"can you wash the dishes",
"library",
"the kids left their toys all over the floor again",
"story",
"clean kitchen",
"have you seen that new movie everyones talking about",
"need more toilet paper",
"delivery",
"recommendation",
"whos emptying the trash",
"lets walk the dog",
"car",
"repayment",
"hours",
"school",
"the light bulb in the hallway needs to be replaced",
"i love spending time in the garden",
"need water",
"tips",
"tv",
"im craving some chocolate chip cookies",
"im thinking of taking up painting as a hobby",
"im thinking of hosting a barbecue party",
"im thinking of adopting a pet from the shelter",
"im planning to take a cooking challenge",
"population",
"im going to clean out the pantry",
"can you grab the laundry",
"i had a dream about traveling to japan",
"its been raining a lot lately hasnt it",
"we should plan a family movie night soon",
"dont forget to buy bread",
"button",
"not sure mean",
"we should plan a game night with friends",
"stain",
"the dogs toys need to be put away",
"conditions",
"can you help me hang these curtains",
"the dogs begging",
"mower",
"sure",
"lower back",
"setting",
"whats your favorite type of music",
"have you watered the plants today",
"im going to start practicing meditation",
"lets go for a drive in the countryside",
"can you turn off the heater",
"laptop charge",
"the ovens preheated",
"sweater grab chilly",
"im going to fix that loose tile in the kitchen",
"messages check",
"whats that over there",
"lost keys",
"can you empty the trash",
"im planning a picnic in the park",
"utensils",
"the sinks leaking",
"study",
"schedule review",
"order groceries",
"eggs",
"equipment",
"command wrong",
"time to clean up",
"car outside",
"can you close the window",
"im thinking of joining a hiking group",
"the dogs water bowl needs to be filled",
"ill do the dishes",
"i need to make a reservation for the car rental",
"im planning to visit a botanical garden",
"headache",
"present",
"groceries order",
"the laundrys done",
"sweets craving",
"im going to tidy up the living room",
"insurance",
"lets grab a snack",
"plan",
"wheres the remote",
"run go for",
"the grocery store is having a sale on fresh produce",
"schedule",
"schedule check",
"too warm",
"feed pets",
"too",
"dinner",
"the mail just arrived can you check it",
"im going to start a mindfulness practice",
"remove",
"check schedule",
"milk buy",
"im going to wash the windows tomorrow",
"lets have a picnic in the backyard tomorrow",
"im planning to visit a nearby hiking trail",
"the acs not working",
"garden",
"im going to start learning spanish soon",
"the presentation went well didnt it",
"bedtime",
"i need to catch up on my emails this afternoon",
"reminder set",
"game",
"im planning to try out a new restaurant",
"have you seen my keys anywhere",
"restaurant",
"good morning how are you today",
"im going to start a savings plan for a vacation",
"im going to start a journaling challenge",
"i need to charge my phone",
"weather forecast check",
"time check",
"i need to make a list of things to pack",
"rome",
"lets order chinese",
"we should plan a family reunion for next summer",
"exercise",
"lawn",
"im going to start a weekly meal prep routine",
"benefits",
"dont forget to feed the cat",
"vitamins take",
"take vitamins",
"remote",
"the book im reading is really captivating",
"im going to start a morning yoga routine",
"lets clean the living room",
"fact",
"books",
"the tvs turned off",
"whoops wrong command",
"im going to clean out the closets",
"im going to clean out the garage soon",
"the weekend went by too quickly didnt it",
"im thinking of joining a book club",
"we should plan a weekend getaway soon",
"purchase",
"back right",
"lets clean the bathroom",
"i need to call the plumber about the leak",
"the cats by the window",
"the cats purring",
"ive been feeling under the weather lately",
"the dishes are piling up in the sink",
"ill water the plants",
"im going to start a daily drawing practice",
"joke",
"im going to start composting my kitchen scraps",
"time to take medicine",
"lets watch a movie",
"tv volume loud",
"time",
"i need coffee",
"sunscreen",
"today date",
"order",
"can you hear me",
"the traffic was terrible on my way home",
"tomorrow",
"im going to clean out the kitchen cabinets",
"episode",
"thanks for watchingi like that",
"nearby",
"vet",
"the bathroom mirror needs to be cleaned",
"calendar",
"set",
"turn down the tv",
"i cant wait for the weekend to relax",
"whos feeding the fish",
"gym",
"walk go for",
"i need to buy a gift for sarahs baby shower",
"task",
"call",
"hardwood",
"im thinking of starting a knitting project",
"im going to start a journaling journey",
"lets order some sushi",
"please",
"membership",
"run",
"plants water",
"the alarms beeping",
"grocery list make",
"oops pen dropped",
"im planning a visit to the art museum",
"i need to return some books to the library",
"center",
"ill be heading to the gym after work",
"the ovens turned off",
"cookbook",
"grocery",
"list",
"turn on music",
"i need to pick up some groceries on the way home",
"ill feed the cat",
"im thinking of starting a new hobby",
"im thinking of adopting a rescue pet from the shelter",
"outside rain",
"im going to start a daily exercise routine",
"bank balance check",
"pet food order more",
"whos washing dishes",
"garden water",
"route",
"someones at the door",
"we should have a movie marathon this weekend",
"is it time for lunch yet",
"the dog needs a walk",
"alarm set",
"clean",
"word",
"turn off lights",
"have you seen the car keys",
"im planning to take a dance class",
"smell",
"im planning to take a pottery class",
"desk organize",
"feeling tired",
"piano",
"sweets",
"i think were running low on milk",
"i need to make a dentist appointment",
"keys lost",
"open",
"im going to start a budgeting journey",
"im planning a barbecue for the fourth of july",
"shopping list make",
"can you recommend a good restaurant for dinner",
"im going to vacuum the living room later",
"lets grab dinner at that new restaurant downtown",
"thank you very much",
"im thinking of trying out a new recipe website",
"chores",
"call",
"bank",
"i need to make a reservation for dinner",
"gear",
"im excited about the concert next weekend",
"i need to schedule a grooming appointment for the dog",
"craving",
"chocolate",
"im planning a day trip to the countryside",
"the phones ringing loudly",
"forecast",
"meeting",
"im planning to do some gardening this weekend",
"im going to start a daily gratitude challenge",
"sorry wrong button",
"the phones vibrating",
"lets clean the bedroom",
"rain",
"i need to finish that report by the end of the week",
"capital",
"water",
"im going to bake cookies for the bake sale",
"clean mess",
"products",
"im planning to take a hiking trip",
"knitting",
"water need",
"do we have any plans for the weekend",
"rates",
"recycling",
"mean sure not",
"habits",
"im planning to explore a nearby nature trail",
"location",
"time to vacuum the carpet",
"the kitchen floor needs to be swept",
"meeting schedule",
"exercises",
"warranty",
"time to feed the fish",
"im going to clean out the garage",
"average",
"turn",
"tired feeling",
"im going to start a diy project",
"rent",
"im hungry",
"ill be right back",
"pollution",
"repair",
"the cats on the couch",
"im going to start a decluttering challenge",
"the cats meowing",
"window open",
"im going to fix that wobbly table leg",
"i need to drop off that package at the post office",
"the cats on the table",
"microwave",
"i need to pick up the dry cleaning tomorrow",
"i need to schedule a haircut appointment",
"im planning to volunteer at the local animal shelter",
"im going to start a daily exercise challenge",
"shuffle",
"im going to start a new workout routine",
"supplies",
"call back later",
"ill take care of it",
"time lunch",
"time for bed",
"traffic",
"whos washing the car",
"lost",
"we should go through the old clothes in the closet",
"the wifis down again",
"the laundry basket is overflowing",
"tallest",
"lets order chinese food",
"the neighbors are having a party tonight",
"the dogs scratching",
"the fridge is full",
"did you catch the game last night",
"ill wash the car",
"ill check the fridge",
"we should clean out the attic",
"any plans for tonight",
"appointment",
"bathroom clean",
"lets plan a barbecue for the weekend",
"do we have any plans for the holidays",
"can you close the door",
"time to clean the windows",
"ill walk the dog",
"the dishwashers full",
"trails",
"turn lights off",
"i need to finish reading that book on my nightstand",
"ill take the trash out",
"laptop",
"did you remember to turn off the lights downstairs",
"keys lost",
"can you fix the faucet",
"account",
"lunch",
"im going to clean out the junk drawer",
"do you want me to grab some milk on my way home",
"the toasters broken",
"charge phone",
"dont forget the milk",
"tv",
"noise",
"can you turn off the ac",
"snooze",
"security",
"the traffic was terrible this morning",
"turn off the stove",
"im considering enrolling in a cooking class",
"im thinking of starting a compost bin",
"im going to start a creative writing challenge",
"we should plan a picnic in the park",
"the phones ringing",
"japanese",
"we should rearrange the furniture in here",
"im going to start a daily meditation practice",
"lets order pizza tonight",
"greeting",
"the fridges lights out",
"we should plan a picnic for next saturday",
"im planning to visit a local farmers market",
"whos taking out the trash",
"lessons",
"phones ringing",
"lights off",
"im thinking of trying out a new art medium",
"calendar check",
"techniques",
"groceries",
"im thinking of redecorating the living room",
"the dog needs to be taken for a walk",
"ive been trying to cut back on caffeine lately",
"doctors appointment make",
"im planning to go on a weekend road trip",
"im going to start organizing the pantry",
"the printer is out of ink again",
"im thinking of starting a vegetable garden",
"trash",
"textbook",
"levels",
"tennis",
"ill close the window",
"photography",
"check news",
"the ovens preheating",
"im thinking of joining a community garden",
"i need to buy a birthday present for mom",
"time to brush the dog",
"the tvs too bright",
"living room tidy up",
"im going to start a journaling habit",
"emergency",
"im thinking of joining a hiking club",
"im going to start a photography challenge",
"birthday",
"short break take",
"whos taking the dog out",
"the acs not working well",
"ill take the dog out",
"payment",
"the laundrys folded",
"status",
"i need to make a reservation for the hotel",
"recycling take out",
"i need to make a dentist appointment for the kids",
"im thinking of trying out a new hobby",
"the ovens smoking",
"time to do laundry",
"errands",
"up",
"shopping",
"im thinking of trying out a new fitness class",
"im going to clean out the garage this weekend",
"recipes",
"thoughts",
"podcast",
"can you turn on the heater",
"did you hear about sarahs promotion at work",
"have you seen my keys",
"interests",
"do you think we need a new vacuum cleaner",
"the pantry shelves need to be organized",
"alarm",
"do you want me to pick up dinner on my way home",
"the plants need water",
"options",
"ive been meaning to redecorate the living room",
"time to water plants",
"did you hear about the new exhibit at the museum",
"im planning to visit a local art gallery",
"spf",
"hear",
"water",
"outside car",
"flight",
"lost keys",
"run errands",
"take short break",
"lets have a potluck dinner with friends",
"agreement",
"meditation",
"lets make breakfast",
"do you want me to pick up some dessert for tonight",
"were out of milk",
"the laundrys still wet",
"plumber",
"im going to start a book club with friends",
"thank you thank you",
"button wrong",
"not",
"unread messages any",
"the wi fi seems to be acting up again",
"flat",
"stretch",
"did you take out the trash",
"can you water the plants",
"plans",
"im going to mow the lawn this weekend",
"im going to start a gratitude journal",
"memory",
"have you tried that new coffee shop on the corner",
"wrong command",
"i need to return that library book tomorrow",
"i need to schedule a dentist appointment",
"mountain",
"im really craving some ice cream right now",
"recipe",
"i need to declutter and organize my closet",
"im planning to attend a cooking class",
"im thinking of volunteering at an animal shelter",
"im considering taking up yoga for stress relief",
"home",
"redecorating",
"lets go for a walk in the park this evening",
"my dog keeps barking at the mailman",
"can you grab the mail",
"the cats sleeping",
"security",
"hows the new project coming along",
"time now",
"time to walk the dog",
"im thinking of getting a new pet",
"ill start dinner",
"im going to clean out the storage closet",
"difference",
"im thinking of getting a new pet",
"have you tried that new recipe i sent you",
"keys",
"im considering going back to school",
"im planning to take a weekend getaway",
"the cats hiding",
"what time is dinner going to be ready",
"budget",
"hobbies",
"thank you",
"the fridge is beeping",
"whats the date today",
"time for a shower",
"later",
"im planning a trip to europe next summer",
"we should organize a game night with friends",
"do you want me to put the laundry in the dryer",
"words",
"notes review",
"we should go for a hike this weekend",
"the car could use a wash",
"i forgot to turn off the lights",
"bank account check",
"im thinking of getting a new plant for my desk",
"craving sweets",
"errands run",
"the kids school bags are by the door",
"card",
"the dogs barking",
"the ovens beeping",
"do you want me to take out the trash",
"im thinking of starting a new hobby",
"the neighbors are having a party tonight arent they",
"back",
"i should start looking for a new job",
"im thinking of starting a daily walking routine",
"ill check the mail",
"health",
"whats the time now",
"pen",
"detergent",
"showtimes",
"im not sure what you mean",
"im planning to declutter my home",
"lunch",
"phone charge",
"i need to make a reservation for the restaurant",
"dining",
"pattern",
"booking",
"take break",
"have you seen my phone charger",
"the kids have soccer practice after school today",
"rain outside",
"i need to schedule a haircut appointment for the kids",
"lights",
"car",
"im going to reorganize my closet this weekend",
"the cat knocked over the plant again",
"contact",
"the tvs too loud",
"whos doing the laundry",
"the dogs whining",
"wrong",
"we should clean out the gutters",
"the garden needs some watering today",
"system",
"buy milk",
"dentist appointment make",
"now time",
"i need to schedule a check up with the doctor",
"im going to fix that squeaky floorboard",
"music",
"i need to schedule a doctors appointment",
"ill clean the bathroom",
"vitamin",
"we should plan a movie night at home",
"whos checking the mail",
"do you want me to start dinner",
"im looking forward to the holiday season",
"smell",
"cleaning",
"im excited for the concert next weekend",
"need more paper towels",
"pet",
"loud",
"time for a snack",
"gas",
"do you want me to pick up some fruit for breakfast",
"charge",
"consumption",
"lunch time",
"we should plan a visit to the zoo",
"dentist",
"whos making breakfast",
"courts",
"adoption",
"friend call",
"im going to fix that leak in the bathroom",
"have you read any good books lately",
"hear me",
"im going to clean out the fridge",
"im going to start a daily gratitude practice",
"temperature",
"update",
"i need to get my car serviced next week",
"did you hear that noise",
"museum",
"do you want me to pick up some bread at the store",
"tire",
"the fridge doors open",
"milk",
"bird feeder refill",
"do you want me to start a load of laundry",
"the cats litter box needs to be cleaned",
"have you seen the cat",
"water plants",
"could you pass me the salt please",
"schedule",
"im going to start a daily meditation challenge",
"im planning a movie night with friends",
"im planning to visit a nearby park",
"timer",
"im thinking of redecorating my bedroom",
"im thinking of trying out a new restaurant",
"the doors locked",
"im feeling a bit tired",
"im going to do laundry later today",
"bicycle",
"disposal",
"we should plan a visit to the botanical gardens",
"the tvs on mute",
"lets make sandwiches",
"whos making coffee",
"the acs too cold",
"bins",
"tv loud",
"the cats playful",
"tutorial",
"ill get the mail",
"lets order takeout",
"mess",
"weekend",
"im thinking of getting a haircut soon",
"conditions",
"thermostat",
"we should plan a barbecue for next weekend",
"i need to make a grocery list",
"break take",
"find charger",
"the living room curtains need to be washed",
"playlist",
"im planning to organize a potluck dinner",
"im going to wash the car this weekend",
"outside",
"flowers",
"city",
"laundry",
"coupons",
"reminder",
"mess clean",
"have you checked the weather forecast for tomorrow",
"the acs not cooling",
"the cats on the bed",
"remedy",
"rainfall",
"oops i dropped my pen",
"phone",
"im out of toothpaste",
"warm",
"grooming",
"refill pitcher",
"whos turning off the lights",
"station",
"time for a quick snack",
"can you walk the dog",
"check",
"can you help me with this",
"oops dropped pen",
"im planning a vacation to hawaii next year",
"im going to start a meditation challenge",
"diy",
"the sunset yesterday was absolutely stunning",
"call parents",
"let me check my calendar",
"warm too",
"the movie we watched last night was fantastic",
"the tvs remotes missing",
"im planning to visit a nearby beach",
"the garbage needs to be taken out",
"im trying to cut down on caffeine",
"shampoo buy",
"im thinking of learning to play a musical instrument",
"where did i put my keys",
"i need to schedule a dentist appointment soon",
"who left the lights on",
"we should plan a hike in the mountains",
"check calendar",
"brush teeth bed",
"break",
"ill do the laundry",
"can you fix the tv",
"can you close the curtains",
"the ovens heating up",
"definition",
"do you want me to start the dishwasher",
"im thinking of volunteering at a local shelter",
"charger",
"run more",
"project",
"interesting",
"tracker",
"the laundrys in the dryer",
"im thinking of adopting a minimalist lifestyle",
"time to brush teeth",
"legs stretch",
"the fridges doors closed",
"country",
"the dogs bed needs to be washed",
"mean",
"the lawn needs to be mowed",
"glasses left",
"back later call",
"the sinks clogged",
"what do you think about redecorating the guest room",
"im thinking of trying out a new recipe book",
"did you hear what happened on the news today",
"ive been binge watching a new tv series",
"the dog needs to be groomed",
"wheres the dogs leash",
"road",
"im going to clean out the refrigerator",
"im planning a hike in the mountains",
"parents call",
"the kids room needs to be tidied up",
"please",
"im going to fix that leaky faucet",
"im planning to host a dinner party",
"do you want me to water the plants",
"mortgage",
"can you fix the light",
"time for a nap",
"printer ink order more",
"dosage",
"score",
"the phones ringing again",
"do you want anything from the grocery store",
"im thinking of hosting a game night",
"go walk",
"time for dinner",
"classical",
"whos doing the dishes",
"im going to start journaling every day",
"youpen",
"lets order pizza",
"time to water the garden",
"yoga",
"insurance",
"i think its raining outside",
"kids bedtime",
"history",
"we should plan a visit to the museum",
"debt",
"im planning a trip to the beach",
"ill wash the dishes",
"coverage",
"drink more water",
"hungry",
"im going to visit my parents this weekend",
"right back",
"fridge clean out",
"have you seen the remote control",
"can you pass the salt please",
"i love listening to podcasts while i cook",
"the tvs glitching",
"whos cooking tonight",
"do you want me to pick up the kids from school",
"the doors stuck",
"i should probably start meal prepping for the week",
"ill call you back later",
"outside",
"im thinking of joining a local sports team",
"clean",
"cooking",
"wrong button",
"i need to schedule a vet appointment for the cat",
"im going to start a daily yoga practice",
"plants",
"im going to start a cooking challenge",
"im planning to enroll in a photography class",
"im thinking of trying out a new recipe",
"theater",
"dry cleaning pick up",
"ill make the bed",
"i need to get my car serviced next week",
"medicine",
"we should plan a hike in the mountains this weekend",
"volume loud tv",
"i need to buy some milk",
"groceries",
"news check",
"we should repaint the walls in the bedroom",
"hours",
"volume",
"knitting",
"lets make some tea",
"the new restaurant downtown has amazing reviews",
"im going to fix that squeaky door hinge",
"the doors unlocked",
"whos letting the dog out",
"volume",
"later back call",
"weather",
"the milks gone bad",
"to do list update",
"i need to schedule a meeting with my boss",
"lets go for a walk",
"supplies",
"cabinet",
"time for lunch",
"im going to start a daily gratitude journey",
"did you catch the game last night",
"hiking",
"im trying to eat healthier these days",
"im going to start a budgeting plan",
"the laundrys piled up",
"too warm",
]

if __name__ == "__main__":
    from nlp import clean_text
    filtered = "\n".join([f"\"{clean_text(phrase)}\"," for phrase in list(set(FALSE_POSITIVES))])
    with open('false_positives.txt', 'w') as file:
        file.write(filtered)