FALSE_POSITIVES = [
"can you fix the faucet",
"phone",
"yoga",
"plan",
"reminder",
"ill make the bed",
"time for lunch",
"im going to start a weekly meal prep routine",
"headache",
"unread messages any",
"im planning a hike in the mountains",
"im going to start a new workout routine",
"can you wash the dishes",
"recipe",
"put away laundry",
"time to water plants",
"the laundrys done",
"cleaning",
"definition",
"im thinking of rearranging the furniture in the living room",
"we should plan a visit to the botanical gardens",
"i had a dream about traveling to japan",
"have you seen my phone charger",
"flight",
"trash take out",
"im going to start composting my kitchen scraps",
"exercise",
"theater",
"im going to start a daily gratitude journey",
"im thinking of redecorating the living room",
"time to feed the fish",
"the mail just arrived can you check it",
"order",
"i need to buy a birthday present for mom",
"milk",
"disposal",
"the acs not cooling",
"im thinking of trying out a new recipe book",
"lets order pizza tonight",
"can you pass the salt please",
"im going to visit my parents this weekend",
"remove",
"meeting",
"courts",
"im considering joining a yoga class",
"i need to schedule a check up with the doctor",
"good morning how are you today",
"rental",
"laundry",
"clean kitchen",
"payment",
"im thinking of adopting a pet from the shelter",
"im going to fix that loose tile in the kitchen",
"can you fix the light",
"did you hear what happened on the news today",
"im going to clean out the pantry",
"vitamins take",
"the laundrys in the dryer",
"im going to start a diy project",
"list",
"im thinking of starting a compost bin",
"feed pets",
"system",
"i need to call the plumber about the leak",
"im going to fix that leak in the bathroom",
"someones at the door",
"do you want me to start dinner",
"keys",
"time for dinner",
"we should plan a hike in the mountains",
"im going to start a budgeting journey",
"i need to schedule a vet appointment for the cat",
"we should plan a family reunion for next summer",
"gear",
"living room tidy up",
"im thinking of joining a community garden",
"time to do laundry",
"cabinet",
"keys lost",
"ill take care of it",
"detergent",
"the cats litter box needs to be cleaned",
"equipment",
"recycling",
"the cats on the table",
"shopping",
"whos doing the dishes",
"the tvs turned off",
"the phones batterys low",
"time to brush the dog",
"lets watch a movie",
"the phones vibrating",
"refill pitcher",
"im going to clean out the refrigerator",
"membership",
"the neighbors are having a party tonight arent they",
"greeting",
"email check",
"the fridge doors open",
"tutorial",
"kids bedtime",
"the living room curtains need to be washed",
"alarm set",
"i need to schedule a haircut appointment for the kids",
"do you want me to water the plants",
"groceries",
"cookbook",
"water plants",
"im thinking of joining a hiking group",
"take vitamins",
"can you grab the laundry",
"ive been feeling under the weather lately",
"im craving some chocolate chip cookies",
"do you want me to pick up the kids from school",
"time to walk the dog",
"call",
"the kids have soccer practice after school today",
"sunscreen",
"we should go for a hike this weekend",
"now time",
"im going to start a daily exercise challenge",
"rain outside",
"remedy",
"craving",
"trash",
"im thinking of trying out a new fitness class",
"bathroom clean",
"we should plan a picnic in the park",
"the phones charging",
"habits",
"i need to buy some milk",
"tire",
"lets have a potluck dinner with friends",
"im going to start a daily exercise routine",
"the phones ringing",
"craving sweets",
"whos making coffee",
"need more toilet paper",
"the alarms beeping",
"fitness",
"thanks for watchingi like that",
"do you want anything from the grocery store",
"im excited for the concert next weekend",
"whos letting the dog out",
"the dogs begging",
"can you fix the tv",
"im feeling a bit under the weather today",
"thermostat",
"camping",
"mean",
"pollution",
"whos taking out the trash",
"whats your opinion on the latest political news",
"im thinking of trying out a new recipe",
"do you want me to pick up some bread at the store",
"the acs not working",
"not",
"im going to start a daily drawing practice",
"ill water the plants",
"i need to get my car serviced next week",
"microwave",
"phones ringing",
"im going to clean out the junk drawer",
"have you watered the plants today",
"sweets",
"ill take the trash out",
"alarm",
"break take",
"shopping list make",
"chocolate",
"do you want me to grab some milk on my way home",
"time for bed",
"the fridge is open",
"im planning to try out a new restaurant",
"time to water the garden",
"im going to start a morning yoga routine",
"bird feeder refill",
"where did i put my keys",
"im planning a barbecue for the fourth of july",
"we should plan a picnic for next saturday",
"the milks gone bad",
"the light bulb in the hallway needs to be replaced",
"agreement",
"im planning a visit to the art museum",
"im planning to do some gardening this weekend",
"hungry",
"mean not sure",
"the ovens beeping",
"water need",
"meditation",
"time for a shower",
"bicycle",
"back right",
"i need to return that library book tomorrow",
"warm",
"calendar check",
"i need coffee",
"dosage",
"need water",
"piano",
"location",
"im thinking of starting a daily walking routine",
"the kids left their toys all over the floor again",
"run",
"im thinking of learning to play a musical instrument",
"whos feeding the fish",
"im planning to go on a weekend road trip",
"textbook",
"have you seen that new movie everyones talking about",
"whos washing the car",
"schedule review",
"i need to make a reservation for the hotel",
"can you help me hang these curtains",
"im planning to visit a nearby hiking trail",
"the bathroom mirror needs to be cleaned",
"im going to clean out the garage soon",
"we should plan a visit to the zoo",
"volume loud tv",
"smell",
"ill check the fridge",
"hear",
"tomorrow",
"the dishwashers full",
"walk go for",
"youpen",
"station",
"can you grab the mail",
"lets clean the living room",
"dining",
"have you read any good books lately",
"i need to make a reservation for the car rental",
"im going to fix that leaky faucet",
"i need to pick up some groceries on the way home",
"car",
"clean mess",
"i need to pick up some groceries after work",
"whos turning off the lights",
"im thinking of volunteering at a local shelter",
"lessons",
"we should plan a barbecue for next weekend",
"back later call",
"sure",
"study",
"ill check the mail",
"the toasters broken",
"thoughts",
"laptop charge",
"im going to clean out the garage this weekend",
"time for a nap",
"im going to start a daily gratitude challenge",
"is it time for lunch yet",
"temperature",
"can you water the plants",
"lets clean the bedroom",
"go walk",
"the tvs remotes missing",
"traffic",
"benefits",
"nearby",
"lets grab dinner at that new restaurant downtown",
"we should rearrange the furniture in here",
"im thinking of hosting a barbecue party",
"project",
"im going to do laundry later today",
"medication",
"im thinking of joining a book club",
"im going to start a cooking challenge",
"school",
"im going to start a mindfulness practice",
"do we have any plans for the weekend",
"im planning a vacation to hawaii next year",
"im thinking of trying out a new recipe website",
"do you want me to put the laundry in the dryer",
"loud",
"whos taking the dog out",
"adoption",
"the printer is out of ink again",
"score",
"contact",
"stretch",
"bank",
"parents call",
"my dog keeps barking at the mailman",
"lets order chinese",
"have you checked the weather forecast for tomorrow",
"hardwood",
"hobbies",
"im planning to visit a local farmers market",
"whos making breakfast",
"what do you think about redecorating the guest room",
"lets clean the kitchen",
"waste",
"we should plan a game night with friends",
"rent",
"ill take the dog out",
"repair",
"time to brush teeth",
"ill wash the car",
"the presentation went well didnt it",
"did you hear that noise",
"tv loud",
"im going to wash the windows tomorrow",
"remote",
"security",
"im going to start a decluttering challenge",
"population",
"have you tried that new coffee shop on the corner",
"status",
"booking",
"im not sure what you mean",
"whoops wrong command",
"im hungry",
"turn down the tv",
"calendar",
"the dogs scratching",
"playlist",
"groceries order",
"the book im reading is really captivating",
"the new restaurant downtown has amazing reviews",
"im going to vacuum the living room later",
"lets have a picnic in the backyard tomorrow",
"could you pass me the salt please",
"turn",
"did you hear about the new exhibit at the museum",
"the laundrys piled up",
"outside car",
"bedtime",
"later",
"im considering enrolling in a cooking class",
"appointment",
"back",
"whos emptying the trash",
"meeting schedule",
"capital",
"im going to clean out the fridge",
"the cats on the couch",
"flat",
"i need to schedule a doctors appointment",
"the phones ringing loudly",
"i need to make a grocery list",
"im planning to visit a nearby beach",
"lunch time",
"im going to clean out the closets",
"wrong command",
"ive been meaning to redecorate the living room",
"i need to finish reading that book on my nightstand",
"clean",
"words",
"oops dropped pen",
"the acs too cold",
"water",
"i need to pick up the dry cleaning tomorrow",
"car outside",
"spf",
"forecast",
"whos doing the laundry",
"button wrong",
"im planning a trip to europe next summer",
"the pantry shelves need to be organized",
"the tvs too bright",
"charger",
"recipes",
"center",
"country",
"i love spending time in the garden",
"friend call",
"window open",
"im planning to declutter my home",
"today date",
"the cats playful",
"ill clean the bathroom",
"im feeling a bit tired",
"sorry wrong button",
"route",
"have you seen the car keys",
"memory",
"exercises",
"do you want me to pick up some eggs on my way home",
"date",
"milk buy",
"trails",
"i need to make a list of things to pack",
"can you close the blinds",
"mower",
"can you close the door",
"im thinking of trying out a new hobby",
"repayment",
"im planning to attend a cooking class",
"can you close the window",
"time to take medicine",
"notes review",
"have you seen my keys anywhere",
"i need to buy a gift for sarahs baby shower",
"oops pen dropped",
"im trying to eat healthier these days",
"hows the new project coming along",
"whos doing dishes tonight",
"command wrong",
"dont forget to buy bread",
"bank balance check",
"the cats meowing",
"doctors appointment make",
"the dogs barking",
"wheres the dogs leash",
"wrong button",
"im thinking of redecorating my bedroom",
"whos checking the mail",
"delivery",
"im planning to take a cooking challenge",
"the lawn needs to be mowed",
"the dogs toys need to be put away",
"im planning to visit a nearby park",
"gas",
"im thinking of taking up painting as a hobby",
"im thinking of joining a local sports team",
"im planning to take a weekend getaway",
"classical",
"hours",
"tracker",
"right back",
"task",
"dinner",
"whats your favorite type of music",
"photography",
"mess",
"tennis",
"im planning to visit a botanical garden",
"we should plan a family game night",
"check news",
"phone charge",
"present",
"ill do the laundry",
"im thinking of trying out a new art medium",
"the doors locked",
"im going to bake cookies for the bake sale",
"the doors stuck",
"museum",
"flowers",
"i think were running low on milk",
"ill be right back",
"the sunset yesterday was absolutely stunning",
"let me check my calendar",
"ill take out the trash",
"hear noise",
"button",
"im thinking of starting a knitting project",
"i need to schedule a haircut appointment",
"im going to start a journaling challenge",
"the bathroom sink is clogged again",
"ill get the mail",
"im going to start a meditation challenge",
"time check",
"the laundrys still wet",
"im going to start a daily gratitude practice",
"have you seen my keys",
"im planning a movie night with friends",
"were out of milk",
"printer ink order more",
"consumption",
"its been raining a lot lately hasnt it",
"episode",
"im thinking of adopting a rescue pet from the shelter",
"we should plan a day trip to the beach",
"whats the time now",
"weekend",
"the bathrooms occupied",
"lets clean the bathroom",
"who left the lights on",
"wheres the dogs bowl",
"the garbage needs to be taken out",
"the phones ringing again",
"do we have any plans for the holidays",
"lets take a break",
"legs stretch",
"time to clean the windows",
"plants water",
"pet",
"recommendation",
"the grocery store is having a sale on fresh produce",
"the dishes are piling up in the sink",
"messages check",
"the dog needs a walk",
"the fridges lights out",
"can you close the curtains",
"can you help me with this",
"ill do the dishes",
"i need to catch up on my emails this afternoon",
"rates",
"ill call you back later",
"lost keys",
"library",
"can you hear me",
"take break",
"im out of toothpaste",
"dentist appointment make",
"buy milk",
"average",
"mean sure not",
"the garden needs some watering today",
"sweets craving",
"knitting",
"i need to finish that report by the end of the week",
"check calendar",
"cooking",
"road",
"the neighbors are having a party tonight",
"news check",
"we should go for a bike ride along the beach",
"mortgage",
"im thinking of getting a new pet",
"hear me",
"im thinking of getting a new plant for my desk",
"im going to tidy up the living room",
"i need to make a dentist appointment",
"recycling take out",
"run errands",
"im going to start a budgeting plan",
"reminder set",
"ill wash the dishes",
"im planning to organize a potluck dinner",
"did you take out the trash",
"rome",
"supplies",
"japanese",
"lunch",
"computer",
"im going to start a journaling journey",
"date today",
"im going to start learning spanish soon",
"vitamin",
"the wi fi seems to be acting up again",
"rainfall",
"the tvs too loud",
"i love listening to podcasts while i cook",
"plants",
"restaurant",
"lets make some tea",
"later back call",
"i need to declutter and organize my closet",
"im planning to take a pottery class",
"short break take",
"the cats sleeping",
"the weekend went by too quickly didnt it",
"the cats by the window",
"we should repaint the walls in the bedroom",
"eggs",
"products",
"any plans for tonight",
"stain",
"the dogs water bowl needs to be filled",
"thank you",
"do you want me to pick up some wine for dinner",
"find charger",
"im planning a trip to the beach",
"lets go for a drive in the countryside",
"do you want me to start the dishwasher",
"up",
"account",
"im going to fix that squeaky door hinge",
"im going to fix that wobbly table leg",
"do you want me to pick up some dessert for tonight",
"pet food order more",
"we should clean out the gutters",
"podcast",
"time lunch",
"lets go for a walk in the park this evening",
"grocery list make",
"lower back",
"bins",
"call back later",
"im planning to take a hiking trip",
"mess clean",
"i cant wait for the weekend to relax",
"tired feeling",
"im thinking of starting a new hobby",
"im going to start journaling every day",
"set",
"showtimes",
"time now",
"warranty",
"im planning a day trip to the countryside",
"lets order chinese food",
"the dog needs to be taken for a walk",
"im thinking of starting a vegetable garden",
"ill start dinner",
"pattern",
"tv",
"card",
"the cat knocked over the plant again",
"im going to clean out the storage closet",
"the dogs whining",
"the fridges doors closed",
"ive been trying to cut back on caffeine lately",
"shuffle",
"have you tried the new restaurant on main street",
"the cats purring",
"we should plan a hike in the mountains this weekend",
"time for a quick snack",
"medicine",
"check",
"im considering taking up yoga for stress relief",
"the movie we watched last night was fantastic",
"glasses left",
"whos turning on the tv",
"im planning to visit a local art gallery",
"i need to call the insurance company",
"im going to clean out the garage",
"warm too",
"order groceries",
"story",
"the ovens preheating",
"time to clean up",
"conditions",
"vet",
"schedule check",
"im really craving some ice cream right now",
"home",
"city",
"we should organize a game night with friends",
"take",
"i think its raining outside",
"update",
"im looking forward to the holiday season",
"whos cooking tonight",
"im planning to take a cooking class",
"ill close the window",
"the lights flickered",
"options",
"im going to start a gratitude journal",
"im going to start a book club with friends",
"levels",
"im going to start a daily meditation challenge",
"im planning to take a gardening class",
"im planning a picnic in the park",
"the fridge is beeping",
"difference",
"im trying to cut down on caffeine",
"im going to start organizing the pantry",
"fact",
"im going to start a creative writing challenge",
"have you tried that new recipe i sent you",
"thank you thank you",
"household",
"to do list update",
"lets order pizza",
"lets plan a barbecue for the weekend",
"im excited about the new restaurant opening",
"dont forget the milk",
"errands",
"the sinks clogged",
"the acs not working well",
"i need to make a reservation for the restaurant",
"break",
"have you seen the cat",
"do you want me to take out the trash",
"tired",
"redecorating",
"the dogs bed needs to be washed",
"run more",
"im thinking of getting a haircut soon",
"im going to start a journaling habit",
"charge",
"drink more water",
"the traffic was terrible this morning",
"the laundrys folded",
"oops i dropped my pen",
"do you want me to pick up dinner on my way home",
"im going to start practicing meditation",
"mountain",
"dont forget to feed the cat",
"whats that over there",
"schedule",
"pen",
"i need to return some books to the library",
"birthday",
"music",
"thank you very much",
"the kids room needs to be tidied up",
"news headlines check",
"we should plan a family movie night soon",
"feeling tired",
"wrong",
"garden water",
"today",
"plumber",
"i need to charge my phone",
"charge phone",
"the ovens preheated",
"im planning to volunteer at the local animal shelter",
"we should plan a visit to the museum",
"lawn",
"insurance",
"i need to schedule a dentist appointment",
"dry cleaning pick up",
"can you empty the trash",
"we should go through the old clothes in the closet",
"the sinks leaking",
"outside rain",
"im going to fix that loose doorknob",
"im thinking of volunteering at an animal shelter",
"the car could use a wash",
"coupons",
"interesting",
"im going to start a savings plan for a vacation",
"we should have a movie marathon this weekend",
"the ovens turned off",
"grocery",
"outside",
"im thinking of trying out a new restaurant",
"im going to mow the lawn this weekend",
"the tvs glitching",
"the cats on the bed",
"laptop",
"open",
"the plants need water",
"we should plan a picnic in the park this weekend",
"ill feed the cat",
"the ovens smoking",
"not sure mean",
"the wifis down again",
"i need to make a dentist appointment for the kids",
"dont forget to lock the door",
"garden",
"im excited about the concert next weekend",
"interests",
"brush teeth bed",
"im going to fix that squeaky floorboard",
"im going to clean out the kitchen cabinets",
"too",
"im planning to take a dance class",
"the kitchen floor needs to be swept",
"im going to start a photography challenge",
"the kids school bags are by the door",
"lets make breakfast",
"im planning to host a dinner party",
"do you think we need a new vacuum cleaner",
"i need to schedule a meeting with my boss",
"tallest",
"im going to start a daily yoga practice",
"have you seen the remote control",
"coverage",
"the fridge is full",
"emergency",
"time for a snack",
"did you hear about sarahs promotion at work",
"game",
"im going to reorganize my closet this weekend",
"diy",
"lost",
"the cats hiding",
"ive been binge watching a new tv series",
"whos washing dishes",
"setting",
"dentist",
"do you want me to start a load of laundry",
"the dog needs to be groomed",
"word",
"im planning to explore a nearby nature trail",
"lets order takeout",
"i need to drop off that package at the post office",
"im planning to enroll in a photography class",
"lets make sandwiches",
"bank account check",
"i need to schedule a grooming appointment for the dog",
"debt",
"im thinking of joining a hiking club",
"desk organize",
"whats the date today",
"im going to start a daily meditation practice",
"reservations",
"utensils",
"hiking",
"rain",
"take short break",
"history",
"can you walk the dog",
"im considering going back to school",
"wheres the remote",
"errands run",
"books",
"please",
"too warm",
"plans",
"run go for",
"ill be heading to the gym after work",
"do you want me to pick up some fruit for breakfast",
"tv volume loud",
"chores",
"lets grab a snack",
"the traffic was terrible on my way home",
"lets order some sushi",
"health",
"i need to schedule a dentist appointment soon",
"im thinking of hosting a game night",
"im thinking of adopting a minimalist lifestyle",
"the tvs on mute",
"gym",
"grooming",
"i need to make a reservation for dinner",
"lets go for a walk",
"budget",
"did you catch the game last night",
"im going to wash the car this weekend",
"techniques",
"fridge clean out",
"purchase",
"we should plan a movie night at home",
"joke",
"i should start looking for a new job",
"the laundry basket is overflowing",
"need more paper towels",
"can you recommend a good restaurant for dinner",
"the ovens heating up",
"we should clean out the attic",
"i should probably start meal prepping for the week",
"shampoo buy",
"check schedule",
"the doors unlocked",
"noise",
"we should plan a weekend getaway soon",
"tips",
"lets walk the dog",
"ill walk the dog",
"sweater grab chilly",
"time",
]

if __name__ == "__main__":
    from nlp import clean_text
    filtered = "\n".join(list(set([f"\"{clean_text(phrase)}\"," for phrase in FALSE_POSITIVES])))
    with open('false_positives.txt', 'w') as file:
        file.write(filtered)