import os

FALSE_POSITIVES = [
    "greeting",
    "the kids school bags are by the door",
    "im excited about the concert next weekend",
    "today",
    "we should plan a picnic in the park this weekend",
    "the dishwashers full",
    "booking",
    "im thinking of starting a new hobby",
    "dosage",
    "fact",
    "im going to clean out the storage closet",
    "time to take medicine",
    "im going to fix that squeaky door hinge",
    "im going to start a mindfulness practice",
    "hey stop",
    "i need to make a dentist appointment",
    "i need to schedule a vet appointment for the cat",
    "too",
    "trash",
    "im planning to host a dinner party",
    "interests",
    "can you help me hang these curtains",
    "im planning to take a cooking class",
    "meeting",
    "charge phone",
    "im thinking of starting a daily walking routine",
    "tallest",
    "medicine",
    "vet",
    "the dog needs to be taken for a walk",
    "time to clean the windows",
    "ill water the plants",
    "im going to clean out the fridge",
    "im going to start composting my kitchen scraps",
    "smell",
    "im planning a visit to the art museum",
    "drink more water",
    "outside car",
    "need more toilet paper",
    "im thinking of getting a new plant for my desk",
    "whos doing the laundry",
    "the acs not working",
    "lets order takeout",
    "lessons",
    "friend call",
    "im going to fix that wobbly table leg",
    "the movie we watched last night was fantastic",
    "school",
    "im going to mow the lawn this weekend",
    "have you tried the new restaurant on main street",
    "im thinking of taking up painting as a hobby",
    "im thinking of adopting a minimalist lifestyle",
    "can you recommend a good restaurant for dinner",
    "lower back",
    "im going to start a meditation challenge",
    "desk organize",
    "oops dropped pen",
    "ill check the mail",
    "im planning to visit a nearby park",
    "can you wash the dishes",
    "need water",
    "products",
    "time to brush teeth",
    "do you want me to water the plants",
    "the kids room needs to be tidied up",
    "ill call you back later",
    "schedule review",
    "im planning to organize a potluck dinner",
    "whos making coffee",
    "lets grab dinner at that new restaurant downtown",
    "delivery",
    "tire",
    "im planning to go on a weekend road trip",
    "i need to schedule a dentist appointment",
    "date",
    "time to walk the dog",
    "window open",
    "set",
    "hobbies",
    "i love spending time in the garden",
    "today date",
    "we should plan a picnic for next saturday",
    "whats the date today",
    "the cats playful",
    "its been raining a lot lately hasnt it",
    "emergency",
    "can you close the window",
    "im planning to take a weekend getaway",
    "the tvs turned off",
    "have you tried that new coffee shop on the corner",
    "music",
    "tennis",
    "definition",
    "cookbook",
    "trash take out",
    "thermostat",
    "dont forget to buy bread",
    "its the same thing",
    "capital",
    "the ovens heating up",
    "lets make breakfast",
    "ill be right back",
    "its out of time many times",
    "the neighbors are having a party tonight",
    "time",
    "warranty",
    "whos taking the dog out",
    "pen",
    "whos turning off the lights",
    "dont forget to lock the door",
    "we should plan a family game night",
    "whos turning on the tv",
    "car outside",
    "the bathrooms occupied",
    "whos emptying the trash",
    "the tvs too loud",
    "run errands",
    "break take",
    "have you watered the plants today",
    "list",
    "spf",
    "the cats on the table",
    "im going to start a creative writing challenge",
    "im excited for the concert next weekend",
    "lets order some sushi",
    "alarm set",
    "lost",
    "ill see you all in some way thanks a lot",
    "lets watch a movie",
    "im thinking of joining a community garden",
    "living room tidy up",
    "rent",
    "up",
    "ill get the mail",
    "the dogs begging",
    "im thinking of joining a book club",
    "printer ink order more",
    "pet",
    "back",
    "not",
    "i need to buy some milk",
    "bank",
    "ill take the trash out",
    "joke",
    "whos letting the dog out",
    "have you read any good books lately",
    "were out of milk",
    "eggs to make sharpened list",
    "bedtime",
    "im going to bake cookies for the bake sale",
    "command wrong",
    "im thinking of joining a local sports team",
    "interesting",
    "kids bedtime",
    "the alarms beeping",
    "tracker",
    "do you want me to pick up some bread at the store",
    "keys",
    "have you checked the weather forecast for tomorrow",
    "im going to start a weekly meal prep routine",
    "we should clean out the gutters",
    "lunch time",
    "im going to clean out the refrigerator",
    "news check",
    "im going to start practicing meditation",
    "can you fix the faucet",
    "dentist appointment make",
    "lets grab a snack",
    "im planning a day trip to the countryside",
    "water need",
    "the new restaurant downtown has amazing reviews",
    "habits",
    "groceries",
    "did you hear what happened on the news today",
    "center",
    "lets go for a walk in the park this evening",
    "we should plan a game night with friends",
    "im planning a movie night with friends",
    "im going to start a budgeting plan",
    "whos washing the car",
    "im planning to visit a local art gallery",
    "coverage",
    "ill take care of it",
    "turn down the tv",
    "oops pen dropped",
    "go walk",
    "its time to go",
    "the phones charging",
    "we should plan a family movie night soon",
    "order",
    "i need to make a list of things to pack",
    "mean",
    "cabinet",
    "grooming",
    "time now",
    "rome",
    "textbook",
    "the dishes are piling up in the sink",
    "the grocery store is having a sale on fresh produce",
    "im going to start a savings plan for a vacation",
    "we should plan a visit to the zoo",
    "my dog keeps barking at the mailman",
    "im planning a vacation to hawaii next year",
    "loud",
    "the weekend went by too quickly didnt it",
    "hear me",
    "tired feeling",
    "debt",
    "im going to start a daily gratitude challenge",
    "birthday",
    "road",
    "country",
    "the doors stuck",
    "im thinking of trying out a new recipe website",
    "what do you think about redecorating the guest room",
    "the sinks leaking",
    "lets go for a walk",
    "the bathroom mirror needs to be cleaned",
    "mess clean",
    "date today",
    "the traffic was terrible on my way home",
    "lawn",
    "the fridge is open",
    "the plants need water",
    "memory",
    "ill be heading to the gym after work",
    "we should plan a day trip to the beach",
    "im going to start a daily meditation practice",
    "have you seen that new movie everyones talking about",
    "email check",
    "can you walk the dog",
    "its great thats up anything",
    "we should go for a bike ride along the beach",
    "flight",
    "we should plan a visit to the botanical gardens",
    "detergent",
    "lets order chinese",
    "i need to pick up some groceries after work",
    "im thinking of volunteering at an animal shelter",
    "the ovens beeping",
    "im planning to do some gardening this weekend",
    "volume loud tv",
    "i think were running low on milk",
    "time for a quick snack",
    "did you hear about sarahs promotion at work",
    "the neighbors are having a party tonight arent they",
    "whoops wrong command",
    "piano",
    "parents call",
    "outside",
    "hardwood",
    "we should plan a movie night at home",
    "im going to clean out the closets",
    "hear noise",
    "we should repaint the walls in the bedroom",
    "podcast",
    "sure",
    "i need to make a reservation for the hotel",
    "equipment",
    "the tvs on mute",
    "put away laundry",
    "hours",
    "lets order pizza",
    "im considering joining a yoga class",
    "hiking",
    "groceries order",
    "recycling",
    "whos cooking tonight",
    "im planning to visit a nearby beach",
    "the mail just arrived can you check it",
    "take short break",
    "thank you okay",
    "turn",
    "recommendation",
    "home",
    "we should go for a hike this weekend",
    "wrong button",
    "im going to start a decluttering challenge",
    "im planning to enroll in a photography class",
    "a lot of them based on our work",
    "dining",
    "benefits",
    "recipes",
    "gas",
    "computer",
    "rainfall",
    "the fridge is full",
    "lets make some tea",
    "bank account check",
    "headache",
    "the fridge is beeping",
    "tv loud",
    "im planning to try out a new restaurant",
    "youpen",
    "is it time for lunch yet",
    "the laundrys piled up",
    "dont forget the milk",
    "unread messages any",
    "diy",
    "im out of toothpaste",
    "im going to start a daily drawing practice",
    "im thinking of starting a vegetable garden",
    "membership",
    "feeling tired",
    "im going to clean out the garage",
    "glasses left",
    "the dogs barking",
    "i need to pick up some groceries on the way home",
    "warm",
    "this is my voice and were talking over the thing in the title and you see pikmin 4 on that and were just talking over the day",
    "milk buy",
    "time to brush the dog",
    "i had a dream about traveling to japan",
    "supplies",
    "im thinking of volunteering at a local shelter",
    "garden",
    "i need to return that library book tomorrow",
    "we should clean out the attic",
    "i need to schedule a meeting with my boss",
    "the ovens turned off",
    "game",
    "have you tried that new recipe i sent you",
    "i need to make a grocery list",
    "fridge clean out",
    "have a good 1",
    "levels",
    "health",
    "have you seen the cat",
    "cleaning",
    "repair",
    "episode",
    "the ovens preheated",
    "errands",
    "the doors unlocked",
    "im thinking of joining a hiking club",
    "i need to buy a birthday present for mom",
    "the phones batterys low",
    "back right",
    "run go for",
    "flowers",
    "calendar check",
    "can you empty the trash",
    "im going to clean out the kitchen cabinets",
    "any plans for tonight",
    "im going to start learning spanish soon",
    "back later call",
    "im thinking of trying out a new hobby",
    "lets have a potluck dinner with friends",
    "water",
    "do we have any plans for the weekend",
    "the cats on the bed",
    "phones ringing",
    "the car could use a wash",
    "the traffic was terrible this morning",
    "the dogs whining",
    "im thinking of adopting a rescue pet from the shelter",
    "i need to make a reservation for the restaurant",
    "phone charge",
    "ill wash the dishes",
    "milk",
    "wrong command",
    "im craving some chocolate chip cookies",
    "walk go for",
    "i think its raining outside",
    "lunch",
    "plan",
    "doctors appointment make",
    "the cats meowing",
    "i think is like it just sounds like someone wanted to be the plan on the internet so im tired",
    "the garbage needs to be taken out",
    "im thinking of hosting a game night",
    "charger",
    "im going to start a photography challenge",
    "later",
    "the phones ringing",
    "did you hear that noise",
    "shuffle",
    "im planning to attend a cooking class",
    "sweater grab chilly",
    "legs stretch",
    "im going to fix that loose doorknob",
    "lets order chinese food",
    "can you close the curtains",
    "the bathroom sink is clogged again",
    "im going to start a journaling challenge",
    "repayment",
    "tutorial",
    "short break take",
    "weekend",
    "sunscreen",
    "its the weather",
    "temperature",
    "remote",
    "can you close the door",
    "i need to schedule a grooming appointment for the dog",
    "the cats sleeping",
    "im planning a hike in the mountains",
    "im planning to take a gardening class",
    "agreement",
    "conditions",
    "im going to wash the windows tomorrow",
    "whos doing dishes tonight",
    "appointment",
    "pollution",
    "dry cleaning pick up",
    "im thinking of redecorating the living room",
    "plans",
    "im trying to cut down on caffeine",
    "errands run",
    "calendar",
    "tired",
    "laptop",
    "lets clean the living room",
    "im going to visit my parents this weekend",
    "im considering going back to school",
    "thank you very much",
    "thank you",
    "craving sweets",
    "yoga",
    "do you want me to start dinner",
    "notes review",
    "im thinking of redecorating my bedroom",
    "buy milk",
    "i need to finish that report by the end of the week",
    "the ovens smoking",
    "medication",
    "ill do the laundry",
    "noise",
    "have you seen my phone charger",
    "or in a tyrant",
    "im thinking of trying out a new fitness class",
    "we should plan a hike in the mountains",
    "ill feed the cat",
    "the garden needs some watering today",
    "the laundrys in the dryer",
    "schedule check",
    "lets walk the dog",
    "whats that over there",
    "im planning to take a dance class",
    "click those to show the ai for art and stuff",
    "im going to start a new workout routine",
    "payment",
    "i need to schedule a haircut appointment",
    "the phones ringing loudly",
    "sorry wrong button",
    "ive been feeling under the weather lately",
    "ill start dinner",
    "im trying to eat healthier these days",
    "the acs not working well",
    "hear",
    "can you fix the tv",
    "break",
    "can you pass the salt please",
    "im going to clean out the garage this weekend",
    "the acs too cold",
    "open",
    "museum",
    "consumption",
    "the dogs bed needs to be washed",
    "contact",
    "shopping",
    "im sure im aware today",
    "find charger",
    "time for a shower",
    "do you want me to pick up some wine for dinner",
    "lets have a picnic in the backyard tomorrow",
    "dentist",
    "im planning to visit a local farmers market",
    "right back",
    "phone",
    "station",
    "do you want me to pick up some eggs on my way home",
    "rental",
    "stretch",
    "time for a nap",
    "water plants",
    "pattern",
    "mean not sure",
    "im planning to take a cooking challenge",
    "oops i dropped my pen",
    "the living room curtains need to be washed",
    "ill make the bed",
    "time to water plants",
    "do you want me to pick up the kids from school",
    "the tvs too bright",
    "the lawn needs to be mowed",
    "ill clean the bathroom",
    "bathroom clean",
    "word",
    "i love listening to podcasts while i cook",
    "laptop charge",
    "fitness",
    "do you want me to put the laundry in the dryer",
    "im excited about the new restaurant opening",
    "charge",
    "exercises",
    "recipe",
    "im thinking of trying out a new art medium",
    "im going to start a cooking challenge",
    "dinner",
    "the fridge doors open",
    "do you want me to pick up some fruit for breakfast",
    "the sinks clogged",
    "the dog needs to be groomed",
    "ill see you next time",
    "tv volume loud",
    "im going to start a daily exercise challenge",
    "im planning a picnic in the park",
    "thank you so much",
    "the cats by the window",
    "im following you",
    "we should have a movie marathon this weekend",
    "run",
    "good morning how are you today",
    "im going to start a morning yoga routine",
    "im thinking of hosting a barbecue party",
    "exercise",
    "ill wash the car",
    "the fridges lights out",
    "population",
    "disposal",
    "system",
    "ill do the dishes",
    "can you hear me",
    "can you close the blinds",
    "the cats litter box needs to be cleaned",
    "button wrong",
    "security",
    "im not sure what you mean",
    "ill walk the dog",
    "laundry",
    "im thinking of starting a compost bin",
    "the cat knocked over the plant again",
    "can you water the plants",
    "status",
    "ive been binge watching a new tv series",
    "have you seen the remote control",
    "i should probably start meal prepping for the week",
    "utensils",
    "tips",
    "the kitchen floor needs to be swept",
    "run more",
    "time for bed",
    "im going to start a book club with friends",
    "im going to start journaling every day",
    "plants water",
    "nearby",
    "can you fix the light",
    "the pantry shelves need to be organized",
    "the acs not cooling",
    "the presentation went well didnt it",
    "sir dont go that way please",
    "take",
    "eggs",
    "im going to do laundry later today",
    "do you want me to grab some milk on my way home",
    "im going to fix that leaky faucet",
    "now time",
    "the tvs remotes missing",
    "the printer is out of ink again",
    "messages check",
    "im thinking of learning to play a musical instrument",
    "did you hear about the new exhibit at the museum",
    "i need to make a reservation for the car rental",
    "restaurant",
    "tomorrow",
    "do you want me to pick up dinner on my way home",
    "perfect oh and thats a blue onion",
    "time for dinner",
    "sweets craving",
    "not sure mean",
    "the doors locked",
    "im going to start a daily meditation challenge",
    "call back later",
    "let me check my calendar",
    "i dont wana that stinky",
    "have you seen my keys",
    "check news",
    "insurance",
    "the phones ringing again",
    "im planning a barbecue for the fourth of july",
    "too warm",
    "alarm",
    "the dogs toys need to be put away",
    "location",
    "the cats on the couch",
    "do you want me to start a load of laundry",
    "who left the lights on",
    "household",
    "wrong",
    "feed pets",
    "i need to call the insurance company",
    "time for a snack",
    "garden water",
    "options",
    "bicycle",
    "im going to start a diy project",
    "project",
    "do you want me to take out the trash",
    "whats the time now",
    "route",
    "where did i put my keys",
    "can you grab the mail",
    "whos checking the mail",
    "im going to reorganize my closet this weekend",
    "remove",
    "check calendar",
    "reservations",
    "do we have any plans for the holidays",
    "you",
    "im planning to explore a nearby nature trail",
    "im hungry",
    "chores",
    "lets clean the bedroom",
    "we should plan a family reunion for next summer",
    "cooking",
    "time to water the garden",
    "bird feeder refill",
    "tv",
    "i need to call the plumber about the leak",
    "im going to start a daily gratitude journey",
    "hows the new project coming along",
    "did you take out the trash",
    "whos washing dishes",
    "to do list update",
    "do you think we need a new vacuum cleaner",
    "im thinking of trying out a new restaurant",
    "classical",
    "im feeling a bit tired",
    "theater",
    "budget",
    "im going to start a budgeting journey",
    "gear",
    "remedy",
    "later back call",
    "check schedule",
    "mess",
    "grocery",
    "ill close the window",
    "lets clean the bathroom",
    "score",
    "clean mess",
    "story",
    "keys lost",
    "the laundrys done",
    "recycling take out",
    "im going to start a journaling journey",
    "whats your opinion on the latest political news",
    "i need to schedule a dentist appointment soon",
    "thank you thank you",
    "ill take the dog out",
    "i need to buy a gift for sarahs baby shower",
    "coupons",
    "im thinking of trying out a new recipe book",
    "craving",
    "sweets",
    "we should plan a picnic in the park",
    "pet food order more",
    "i need to charge my phone",
    "redecorating",
    "do you want me to start the dishwasher",
    "photography",
    "warm too",
    "the tvs glitching",
    "im going to start a journaling habit",
    "i should start looking for a new job",
    "im going to clean out the pantry",
    "camping",
    "mountain",
    "the ovens preheating",
    "thanks for watchingi like that",
    "we should organize a game night with friends",
    "car",
    "ive been meaning to redecorate the living room",
    "time to feed the fish",
    "lets clean the kitchen",
    "wheres the dogs bowl",
    "rain",
    "i need to drop off that package at the post office",
    "adoption",
    "flat",
    "whos making breakfast",
    "city",
    "okay collect all the treasures okay",
    "im looking forward to the holiday season",
    "setting",
    "i need to pick up the dry cleaning tomorrow",
    "the wi fi seems to be acting up again",
    "im planning to declutter my home",
    "clean",
    "hungry",
    "someones at the door",
    "im feeling a bit under the weather today",
    "meeting schedule",
    "bank balance check",
    "do you want anything from the grocery store",
    "meditation",
    "the lights flickered",
    "clean kitchen",
    "bins",
    "im going to start organizing the pantry",
    "dont forget to feed the cat",
    "study",
    "im losing my love in your heart im in your heart im over somewhere in your heart im over somewhere in your heart im over in your heart",
    "we should plan a visit to the museum",
    "the light bulb in the hallway needs to be replaced",
    "im going to tidy up the living room",
    "gym",
    "im planning a trip to the beach",
    "i need to schedule a haircut appointment for the kids",
    "please",
    "ive been trying to cut back on caffeine lately",
    "could you pass me the salt please",
    "we should plan a barbecue for next weekend",
    "ill check the fridge",
    "im considering enrolling in a cooking class",
    "account",
    "time to clean up",
    "average",
    "the cats hiding",
    "i need to catch up on my emails this afternoon",
    "well try to do that",
    "im planning to visit a botanical garden",
    "i need to make a dentist appointment for the kids",
    "we should plan a weekend getaway soon",
    "refill pitcher",
    "the sunset yesterday was absolutely stunning",
    "the kids left their toys all over the floor again",
    "difference",
    "button",
    "do you want me to pick up some dessert for tonight",
    "rain outside",
    "take vitamins",
    "i need to make a reservation for dinner",
    "vitamins take",
    "the laundry basket is overflowing",
    "plants",
    "schedule",
    "im thinking of adopting a pet from the shelter",
    "order groceries",
    "im going to start a gratitude journal",
    "mean sure not",
    "mower",
    "im planning a trip to europe next summer",
    "lets order pizza tonight",
    "mortgage",
    "im thinking of trying out a new recipe",
    "playlist",
    "thats the only priority you can tell you good",
    "take break",
    "showtimes",
    "grocery list make",
    "we should rearrange the furniture in here",
    "im considering taking up yoga for stress relief",
    "the phones vibrating",
    "wheres the dogs leash",
    "can you grab the laundry",
    "just trying to make it kind of fun by making cute little characters",
    "vitamin",
    "the toasters broken",
    "lost keys",
    "library",
    "the laundrys still wet",
    "i need to get my car serviced next week",
    "i need to schedule a check up with the doctor",
    "the dogs water bowl needs to be filled",
    "purchase",
    "the wifis down again",
    "lets go for a drive in the countryside",
    "im going to vacuum the living room later",
    "im going to start a daily exercise routine",
    "whos taking out the trash",
    "shampoo buy",
    "even so for those that have been planted",
    "news headlines check",
    "lets plan a barbecue for the weekend",
    "lets take a break",
    "i need to return some books to the library",
    "whos doing the dishes",
    "courts",
    "japanese",
    "the fridges doors closed",
    "lets make sandwiches",
    "the book im reading is really captivating",
    "thoughts",
    "rates",
    "outside rain",
    "reminder",
    "the kids have soccer practice after school today",
    "im going to fix that squeaky floorboard",
    "im thinking of getting a new pet",
    "im going to clean out the junk drawer",
    "im planning to take a hiking trip",
    "im thinking of rearranging the furniture in the living room",
    "im planning to take a pottery class",
    "traffic",
    "have you seen my keys anywhere",
    "time check",
    "trails",
    "im going to fix that loose tile in the kitchen",
    "i need to declutter and organize my closet",
    "call",
    "im planning to volunteer at the local animal shelter",
    "the dogs scratching",
    "im thinking of joining a hiking group",
    "chocolate",
    "techniques",
    "brush teeth bed",
    "update",
    "plumber",
    "im going to start a daily gratitude practice",
    "im going to clean out the garage soon",
    "i need coffee",
    "time to do laundry",
    "im going to wash the car this weekend",
    "im really craving some ice cream right now",
    "i need to schedule a doctors appointment",
    "books",
    "task",
    "im going to fix that leak in the bathroom",
    "stain",
    "waste",
    "forecast",
    "need more paper towels",
    "the cats purring",
    "the laundrys folded",
    "im going to start a daily yoga practice",
    "i need to finish reading that book on my nightstand",
    "card",
    "im planning to visit a nearby hiking trail",
    "whats your favorite type of music",
    "microwave",
    "i cant wait for the weekend to relax",
    "have you seen the car keys",
    "time for lunch",
    "whos feeding the fish",
    "knitting",
    "wheres the remote",
    "words",
    "ill take out the trash",
    "history",
    "we should go through the old clothes in the closet",
    "did you catch the game last night",
    "the milks gone bad",
    "the dog needs a walk",
    "time lunch",
    "im thinking of getting a haircut soon",
    "present",
    "check",
    "can you help me with this",
    "im thinking of starting a knitting project",
    "reminder set",
    "we should plan a hike in the mountains this weekend"
]

false_positives_path = os.path.join(os.path.realpath(os.path.dirname(__file__)), 'false_positives.txt')

if not os.path.exists(false_positives_path):
    with open(false_positives_path, 'w') as file:
        file.write("\n".join(FALSE_POSITIVES))
else:
    with open(false_positives_path, 'r') as file:
        FALSE_POSITIVES = file.readlines()
        print("Loaded false positives")

def add_false_positive(text: str):
    print("False positive saved")
    with open(false_positives_path, 'a') as file:
        file.write(f"\n{text}")

if __name__ == "__main__":
    from preprocessing import clean_text
    filtered = "\n".join(list(set([f"\"{clean_text(phrase)}\"," for phrase in FALSE_POSITIVES])))
    print(filtered)